// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSBBskOT7cvZhFMdwF7LS9fRYGd7SeqiU',
    appId: '1:777597872595:android:8f3d46605ad3a26a03a726',
    messagingSenderId: '777597872595',
    projectId: 'hopelinker-60302',
    storageBucket: 'hopelinker-60302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF30W62JBB0grjeZnHhSkjyIXBFtO-728',
    appId: '1:777597872595:ios:d52809c84db203d403a726',
    messagingSenderId: '777597872595',
    projectId: 'hopelinker-60302',
    storageBucket: 'hopelinker-60302.firebasestorage.app',
    iosBundleId: 'com.example.hopelinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF30W62JBB0grjeZnHhSkjyIXBFtO-728',
    appId: '1:777597872595:ios:d52809c84db203d403a726',
    messagingSenderId: '777597872595',
    projectId: 'hopelinker-60302',
    storageBucket: 'hopelinker-60302.firebasestorage.app',
    iosBundleId: 'com.example.hopelinker',
  );

}